from typing import Protocol
from uuid import UUID

from app.schemas.hold import HoldResponse
from app.schemas.item import ItemCreate, ItemResponse, ItemStatus, ItemUpdate


class ItemRepository(Protocol):
    async def create(self, data: ItemCreate) -> ItemResponse: ...
    async def get_by_id(self, item_id: UUID) -> ItemResponse | None: ...
    async def update(self, item_id: UUID, data: ItemUpdate) -> ItemResponse | None: ...
    async def delete(self, item_id: UUID) -> bool: ...
    async def update_status(
        self, item_id: UUID, status: ItemStatus
    ) -> ItemResponse | None: ...


class HoldRepository(Protocol):
    async def create(self, item_id: UUID, buyer_id: UUID) -> HoldResponse: ...
    async def get_by_item_id(self, item_id: UUID) -> HoldResponse | None: ...
    async def confirm(self, item_id: UUID, role: str) -> HoldResponse: ...
    async def release(self, item_id: UUID) -> bool: ...
